export enum SpeakerName {
  None = "",
  MikaelBrevik = "Mikael Brevik",
  DavidDinka = "David Dinka",
  VikasGupta = "Vikas Gupta",
  YoeriOtten = "Yoeri Otten",
  JuliaKuhley = "Julia Kuhley",
  LizaHanssonAndStinaJanson = "Liza Hansson & Stina Janson",
  TonjeEvanger = "Tonje Evanger",
  JacobBerglund = "Jacob Berglund",
  MariusKrakeli = "Marius Krakeli",
  AnitaSteinstad = "Anita Steinstad",
  JonasLillevold = "Jonas Lillevold",
  AndreasHartveit = "Andreas Hartveit",
  ChristianBrevik = "Christian Brevik",
  MalinCKarlsen = "Malin C. Karlsen",
  AndersHammervold = "Anders Hammervold",
  EliseKristiansen = "Elise Kristiansen",
  OlePetterKlæstad = "Ole Petter Klæstad",
  RolfAndersStorset = "Rolf Anders Storset",
  KristofferNordström = "Kristoffer Nordström",
  ThomasLyngtunHansen = "Thomas Lyngtun Hansen",
  TrulsHenrikJakobsen = "Truls Henrik Jakobsen",
  NikolaiNormanAndersen = "Nikolai Norman Andersen",
  VegardIngebrigtsenFeste = "Vegard Ingebrigtsen Feste",
  HildegunnVada = "Hildegunn Vada",
  TomasJanson = "Tomas Janson",
}
